### ISSUE TITLE
I don't think that the 'DBAccess' class is thread-safe

### ISSUE THREAD

**Issue by Adam-Sharpe** [SenecaCDOT-BigBlueButton/SenecaBBB#182]
While testing stuff out, a few times I would get a null pointer exception on the console. Something usually like this (the timestamp is not correct):

Jan 15, 2015 1:03:30 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [/SenecaBBB] threw exception [java.lang.NullPointerException] with root cause
java.lang.NullPointerException
    at com.mysql.jdbc.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:830)
    at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5774)
    at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5693)
    at db.DBAccess.queryDB(DBAccess.java:117)
    at sql.Lecture.getAllProfessorCourse(Lecture.java:176)
    at org.apache.jsp.create_005fevent_jsp._jspService(create_005fevent_jsp.java:157)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:724)

The stack trace indicated that the cause was line 117 of:

https://github.com/SenecaCDOT-BigBlueButton/SenecaBBB/blob/master/web-app/src/db/DBAccess.java

I haven't looked at it too carefully, but I think the problem is because a lot of the SQL stuff is a property of DBAccess, and (according the comments) DBAccess is a singleton on a session, if the same session triggers two calls to the 'DBAcess::queryDB' method before the other has completed, both threads may be reading and writing the same properties at the "same time" (interwoven). This is because internally, Tomcat spawns a new thread for every request (not every session), and uses request.getSession() to obtain the session instance. This means that two distinct requests can be tied to the same session, which means that two or more threads handling different requests can be operating on the same session instance.

A quick fix would be to simply add "synchronized" to all the methods (locking the properties of "DBAcccess"), or making the variables local to the functions. I would need look more closely at it to find a better solution... What do you guys think?

Also, I need a way to programmatically test this, because clicking very fast between pages usually doesn't trigger the error (I only got it twice after trying for a long time).

**Comment by capilkey** [comment]
I could be mistaken, but are you sure that the page rendering is multi-threaded? The only potential problem that I can see is if someone tries to load two pages at once.

**Comment by Adam-Sharpe** [comment]
I think the problem happens before the rendering occurs. Looking at the exception and stack trace, my understanding of what happens is this:

Thread 1: Line 112 executes, and returns a result set with 5 columns (let's say), and assigns it to '_rs'.

Thread 1: Line 113 executes, returns a column count of 5 (DB column counts use base 1 arrays), assigning it to its 'colCount'.

THREAD SWITCH HAPPENS!

Thread 2: Line 112 executes, and returns a result set with 3 columns (let's say). Since the result set variable '_rs' is a shared variable (since both threads are on the same instance of DBAccess), the old result set from thread 1 is overwritten.

... more stuff happens in thread 2, and then

THREAD SWITCH HAPPENS!

Thread 1: Goes about it's business, until it gets to line 117. Then, its colCount is still 5, but its iterating over records with only 3 rows of data (from thread 2). In addition to iterating of the wrong result set, when '_rs.getString(i)' happens with values greater than 3, a null pointer exception is thrown.

Again, because there are so few records in the databases, the queries generally happen quickly, so this is hard to replicate, but with more records it might be easier to see.

**Comment by capilkey** [comment]
By "page rendering" I meant the step where the JSP file is turned into an HTML page before being sent to the user. I'm pretty sure each page only has one thread because the JSP file runs sequentially. There's a threading issue if more than one page is loaded at the same time because each will access the database, but if you were just loading one at a time I don't think threads are the cause of your exception.

**Comment by Adam-Sharpe** [comment]
You are right that JSP scriptlets each have there own thread, but the DBAccess class is session-scoped, meaning that it can be shared by multiple requests that belong to the same session.

After looking around some more, I am sure that I am right. I tested it by causing the DBAccess to wait for some period of time after each row was parsed, making it more likely that the threads for each request would get switched out, and trip each other up. It consistently reproduced the error. After making the variables local, or synchronizing the method, the problem disappeared. I will push my fix.

**Comment by amolbhanushali** [comment]
Hello Adam,

I am also facing similar problem.

Could you kindly help me to understand and fix the issue with below details
1) I have db helper class where static getdbconnection method is defined.
2) All the methods in db helper class is static.
3) All the db query methods are defined in this class which will be called by Servlets.

_After making the variables local, or synchronizing the method, the problem disappeared._

which variables you have made local and which method you have made synchronized?

**Comment by amolbhanushali** [comment]
Hello Adam,

Got the fix. 
PreparedStatement, dbConnection and Resultset all changed to local variable for methods and my application works without any issues.
